site_name: Expense Tracker App
nav:
  - Functional and Use Case Documentation: index.md
  - Scope: scope.md
  - Requirement: Requirements.md
  - Use Case: Use-Case.md
  - Data Modeling: Data-Modeling.md
  - Data Flow Diagram: Data-Flow.md
  - Security: Security.md
  - Architecture: Architecture.md
  - Tech Stack: Tech-Stack.md
  - Test Plan: Test-Plan.md
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format




